AWSTemplateFormatVersion: "2010-09-09"
Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
Outputs:
  BucketName:
    Value: !Ref StaticSiteBucket